### ISSUE TITLE
working on areas

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#101]
For Allen: 
We need to double check the scaled areas for Fig 3A

**Comment by ahhurlbert** [comment]
Let me know once you've gotten the area assignments fixed (when we last went over it together, the largest spatial grains had the smallest areas and vice versa), and then I'll give this a thorough check

**Comment by ssnell6** [comment]
fixed. deleted old files and created a single area file called "scaled_areas_3_1.csv"
