### ISSUE TITLE
histograms and beta distributions

### ISSUE THREAD

**Issue by bsevansunc** [hurlbertlab/core-transient#18]
I've updated the histogram plots. The beta distribution is now shown between 1/nTime and 1-1/nTime where nTime is the number of time intervals in the sample.  I've noticed that the beta distribution doesn't seem to be capturing the distribution of the data on the left side of the plot (towards transients). Prior to making more of these, I'm going to move onto to making the summary plots across sites (grouping by system and taxonomic class) but I was wondering if you guys have any suggestions regarding these beta distributions?

**Comment by ahhurlbert** [comment]
I don't think 1-1/nTime should be the upper limit of the interval over which beta is shown. For example, see p. 494. The line should extend to the equivalent of halfway through the bar representing 1.0. But separate from how much of it we should see, perhaps we need to revisit how it's being fit (e.g. is it being fit to some scaled data, and then rescaled back; are these choices appropriate, etc...).

**Comment by bsevansunc** [comment]
Sounds good, will look into it. Also, I put more plots up in the plots
folder, let me know what you think and I'll adjust as needed.

**Comment by ahhurlbert** [comment]
They look good. I'm thinking an alternative to the plots showing average percent core and transient by system and taxa would be a stacked bar showing core, neither, and transient in that order. This means we lose the ability to easily show variation within a group (i.e. the error bars), but it might help make it easier to see the extent to which species truly tend to be in one of the extreme modes versus the neither category.
