### ISSUE TITLE
Dataset prioritization

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#19]
Can we add a Priority column to the data_sources_table? This will allow others (e.g. Zack) to know where to initially focus efforts.

Make this categorical (4 or 5 categories) based on a sort of nTimes and nSites and underrepresented taxa...

**Comment by bsevansunc** [comment]
Will do. Also, this morning I added a plot of bimodality (y axis) by the
number of individuals at a site (x axis) to the output folder
-> output/plots/bimod_by_indiv.pdf

Is this the plot you were looking for (note: in rough draft form), or
should I be scaling bimodality by the number of individuals? If the latter,
we should discuss how this would work. I'll be back in the lab tomorrow.

Brian S Evans

(o>
/  )
 *||*  ----------------------------------------
PhD candidate
Ecology Curriculum
University of North Carolina
Biologist/Spatial Analyst
Smithsonian Migratory Bird Center
--------------------------------------------
