### ISSUE TITLE
date assignment for dataset 208

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#21]
After finding insufficient record data on a per-day basis, I limited the data to per-month and it seems that there is plenty of data to be cleaned as per-month.  But I don't know a good way of converting year- month from this format (2003-05) to decimal years in the dataset.  Month ranges where data was taken in this set are May-Sept only and shorter periods within that range.

**Comment by bsevansunc** [comment]
substring the year character string and convert to numeric. Do the same with the month character string. Create a new decimal month numeric vector by dividing the month by 12. Add the year and and decimal month numeric vectors.

**Comment by ahhurlbert** [comment]
We tried this for awhile but then decided that almost all datasets will have an annual temporal resolution. This should be the default level at which data are temporally aggregated unless there is obvious reason to go finer which should be well documented in the data cleaning script.
