### ISSUE TITLE
REMINDER: Michael needs access to data submodule

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#22]
Title pretty much explains it all..

**Comment by bsevansunc** [comment]
Hi Michael, can you check whether you can access the data folder online? Either click on the data hyperlink on https://github.com/hurlbertlab/core-transient or go to https://github.com/hurlbertlab/core-transient-datasets
Thanks!

**Comment by bsevansunc** [comment]
Ethan -- I now have the sub-repository working fine on my computer and am unsure as to why Michael can't push and pull into it. Allen just did -- git submodule init -> git submodule update and got a permission error on the update. Are we missing a step? What are the steps required?

**Comment by ahhurlbert** [comment]
@ethanwhite Specifically, how should I go about cloning the repo / sub-repo combo on a new machine? Just clone the main repo, and then the git submodule commands? Getting a permissions / key error, SSH-related? Obviously I got this to work on my office machine at some point....

**Comment by ethanwhite** [comment]
It should be:

```
git clone git@github.com:hurlbertlab/core-transient.git
cd core-transient/
git submodule init
submodule uppdate
``` 

It sounds like you have a permissions issue, but in checking this out it also appears that someone rewrote the history in `core-transient-datasets` at some point, which is now resulting in git trying to checkout a commit from that repository that doesn't exist. I'll see about fixing that now. To address the permissions problem I'll probably need to Skype in and look at what's going on on the individual machine.

**Comment by ethanwhite** [comment]
There were a couple of typos in the commands above. I've fixed them now.

**Comment by ethanwhite** [comment]
OK, after the fix in 6ae3d7373fb9384c27bdeffeae6ada4b82dcb79b the commands above work fine using properly configured ssh keys. It should also work using https, but I haven't tested it. I'm happy to set up some time to screen share and figure out what's going on with individual computers if there are still issues.

**Comment by ahhurlbert** [comment]
@ethanwhite
git clone git@... did not work ("Permission denied (publickey)") but
git clone https://... did. But then subsequent steps did not:

```
$git submodule init
Submodule 'data' (git@github.com:hurlbertlab/core-transient-datasets.git) registered for path 'data'

$ git submodule update
Cloning into 'data'...
Warning: Permanently added the RSA host key for IP addres...
Permision denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repo exists.
```

So it seems it is a key issue that maybe would go away if I were able to git clone the main repo using git@github.com in the first place?

**Comment by ethanwhite** [comment]
Ah, I see. I set this up to use ssh keys, see:
https://github.com/hurlbertlab/core-transient/blob/master/.gitmodules

So, in order to use this folks would need to use keys. I'm also happy to change this if the people regularly accessing this would rather use https.

**Comment by ethanwhite** [comment]
Let me know whether you'd like me to change this or help folks set up keys. Here's a good starting point for keys:
https://help.github.com/articles/generating-ssh-keys
