### ISSUE TITLE
broadening lat-lon site data for dataset 97

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#24]
This dataset (ArcOD Plankton) has sites listed by catch method (ie general location, net type, mesh size) and lat-long all within the same string of each row.  There is a wide variety of decimal places that each lat-long is listed by, and because of that there are a ton of unique sites that have very low sample sizes.  Since there are so many different lengths of each string, I'm not sure that I can just substring the lat-longs from each site, then round to nearest 1 or 2 to broaden the data.  Is there a way I can just extract these specific numbers from each string?  Or, more important, is there an overall better way to group sites by a slightly larger lat-long grain size?  Am I even making sense with this question?

**Comment by bsevansunc** [comment]
Hey Michael, hold off on that dataset for now, as well as any lat-long
based dataset. In our meeting yesterday afternoon we decided we need to
change course slightly on datasets for which sites are derived using
lat-longs. If you need a dataset to format, a good place to go at this
point would be to re-format dataset 208. I'll sit with you a bit tomorrow
if you're around to describe the new workflow (and will write something up
about it as well).

Brian S Evans

(o>
/  )
 *||*  ----------------------------------------
PhD candidate
Ecology Curriculum
University of North Carolina
Biologist/Spatial Analyst
Smithsonian Migratory Bird Center
--------------------------------------------

**Comment by ahhurlbert** [comment]
As a marine dataset with samples only given by lat-longs, this dataset is inappropriate for current purposes. Closing issue.
