### ISSUE TITLE
checking Michael's script for weekly designation of decimal year (dataset 208)

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#25]
Just posting this as a heads up to check over my script for cleaning the year column for dataset 208.  I think I did all the correct simple math to get decimal year in a weekly format.  But I could also be way off....

**Comment by mauriemma** [comment]
Also, I posted the new file in the data submodule as "dataset_208_new", I didn't want to stir any issues trying to replace the old 208 file.

**Comment by bsevansunc** [comment]
Technically, the time is just identifiers, so it should be fine. I'll have
a look over your code tomorrow though. I'll also have the new formatting
code in place by then and we can walk through it on Monday.

Brian S Evans

(o>
/  )
 *||*  ----------------------------------------
PhD candidate
Ecology Curriculum
University of North Carolina
Biologist/Spatial Analyst
Smithsonian Migratory Bird Center
--------------------------------------------
