### ISSUE TITLE
time strikes again

### ISSUE THREAD

**Issue by bsevansunc** [hurlbertlab/core-transient#27]
Michael, Allen and I just talked about the temporal grain issue and decided that **annual** samples should be the default. This is simplify the process further because you will no longer have to make any temporal grain decisions when creating the propOcc data frame. I will change the formatting template today.

**Comment by ahhurlbert** [comment]
@mauriemma @bsevansunc Note that if you refer to the Github username in your message/issue, they will receive an email notification regardless of whether they're following the repo.

Can be useful as an alternative to "assigning" an issue if you're just notifying or having a chat.
