### ISSUE TITLE
no count field for dataset 234

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#29]
there are no fields that represent count in this dataset.  But there are several occurrences of single species at each site and time sample, so I believe count can be extracted.  Would ddply be best for this situation?

**Comment by ahhurlbert** [comment]
Yes, for small mammal datasets and bird banding datasets, every row represents an individual and so count must be extracted by summing rows over time and site id's. Is currently done using ddply in the data cleaning script.
