### ISSUE TITLE
choosing levels of spatial & temporal subsampling

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#30]
@bsevansunc 

For each site:
  For every combination of w (spatial subsampling) and z (temporal subsampling):
    Count the number of years of data exceeding these thresholds
    If Count > YearThreshold (i.e. min # years to calc occupancy in a dataset)
      That site, w, z, combination is assigned a value of 1
    Else
      0
   end
end

Summing those values across w, z combinations gives the number of sites that have at least YearThreshold years of data at that combination of w and z.

Now find the largest combination of w and z (??: w/w_max + z/z_max  ??) that has at least X% (e.g. 20%) of sites exceeding the year threshold.

See subsampling_test_datasets.r for some test datasets to verify that the script chooses the subsampling levels properly.

**Comment by bsevansunc** [comment]
Finished creating the script that does this, will test on the test datasets tomorrow.

**Comment by ahhurlbert** [comment]
The core-transient_functions no longer attempt to identify levels of spatial and temporal subsampling objectively, but rely on the user to define those scales. The functions simply confirm whether there are data that are sufficient for analysis at those scales.
