### ISSUE TITLE
site issues with datasets 124 and 97

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#33]
these datasets have sites with a lot of unnecessary info, except for lat-long data.  All the data is separated by underscores, but data has varying numbers of types of info and varying numbers of characters.  So couldn't exclusively separate lat_longs from the rest of the data.  As of now, the sites in the formatted version of the dataset are just the last grouping of characters in the site data that include lat_longs, but also may include extra underscores, site numbers, other site data, etc.  See the formatted datasets, fomatting table site notes, and scripts to get a better idea

**Comment by ahhurlbert** [comment]
As a marine dataset with samples only given by lat-longs, this dataset is inappropriate for current purposes. Closing issue.
