### ISSUE TITLE
Site issues in datasets 71 and 72

### ISSUE THREAD

**Issue by wlarsen2** [hurlbertlab/core-transient#34]
For both of these datasets, the raw site entries have a lot of unnecessary information separated by underscores. I am not sure which information should be used, and it is difficult to remove unnecessary information because of the varying lengths of each entry.
 
For example (Dataset 71): 

"Russia_White_Sea_E35_Kandalaksha_Bay_90_bottle_category_changed_from_unidentified_flagellates" 

For dataset 71, the metadata link I got from OBIS gave very little information: http://www.vliz.be/en/imis?module=dataset&dasid=3846. I downloaded the original dataset from OBIS at http://www.iobis.org/mapper/?dataset=1559 (click on "show results" and then "download"), and it looks like the original dataset had the correct site entries in separate columns along with lat/long data. I think we would either have to find a way to extract the useful site information from the long-winded site entries in the dataset we have or use the original dataset from OBIS, but without the metadata it isn't clear which would work better. 

For dataset 72, which is not on OBIS, I could only find a paper which uses the dataset: http://wsbs-msu.ru/res/DictionaryAttachment/395/DOC_FILENAME/Pertsova_Kosobokova_Zooplankton%20of%20the%20White%20Sea_2003.pdf. On page 2, it names some station labels, which can sometimes be seen in the site entry in between other numbers separated by underscores, but often none of the numbers or characters in the site entry resemble any of the station labels.

**Comment by ahhurlbert** [comment]
Will,

Can you repost with 1 dataset per issue

Thanks,
Allen

**Comment by wlarsen2** [comment]
Sorry about that! They are in separate issue posts now.
