### ISSUE TITLE
Dataset 71 site issue

### ISSUE THREAD

**Issue by wlarsen2** [hurlbertlab/core-transient#35]
For this dataset, the raw site entries have a lot of unnecessary information separated by underscores. I am not sure which information should be used, and it may be difficult to remove unnecessary information because of the varying lengths of each entry.

For example (Dataset 71):

"Russia_White_Sea_E35_Kandalaksha_Bay_90_bottle_category_changed_from_unidentified_flagellates"

For dataset 71, the metadata link I got from OBIS gave very little information: http://www.vliz.be/en/imis?module=dataset&dasid=3846. I downloaded the original dataset from OBIS at http://www.iobis.org/mapper/?dataset=1559 (click on "show results" and then "download"), and it looks like the original dataset had the correct site entries in separate columns along with lat/long data. I think we would either have to find a way to extract the useful site information from the long-winded site entries in the dataset we have or use the original dataset from OBIS, but without the metadata it isn't clear which would work better.

**Comment by ahhurlbert** [comment]
As a marine dataset with samples only given by lat-longs, this dataset is inappropriate for current purposes. Closing issue.
