### ISSUE TITLE
Dataset 72 site issue

### ISSUE THREAD

**Issue by wlarsen2** [hurlbertlab/core-transient#36]
For this dataset, the raw site entries have a lot of possibly unnecessary numbers and letters separated by underscores. I am not sure which information should be used, and it may be difficult to remove unnecessary information because of the varying lengths of each entry.

For example (dataset 72): 

2ws98__10_B-2_270_100_200

For dataset 72, which is not on OBIS, I could only find a paper which uses the dataset: http://wsbs-msu.ru/res/DictionaryAttachment/395/DOC_FILENAME/Pertsova_Kosobokova_Zooplankton%20of%20the%20White%20Sea_2003.pdf. On page 2, it names some station labels, which can sometimes be seen in the site entry in between other numbers separated by underscores, but often none of the numbers or characters in the site entry resemble any of the station labels.

**Comment by ahhurlbert** [comment]
As a marine dataset with samples only given by lat-longs, this dataset is inappropriate for current purposes. Closing issue.
