### ISSUE TITLE
Dataset 85 years and sites different from source dataset

### ISSUE THREAD

**Issue by wlarsen2** [hurlbertlab/core-transient#37]
I couldn't find any useful metadata for this dataset, but I found the original dataset online at http://www.emodnet-biology.eu/portal/index.php?dasid=1037# (Click on 'datasets' and then the 'show data' icon under view). It seems like dataset 85 in the raw datasets folder is a subset of the original that only includes years 1992-2003, though the original goes back as far as 1986. More importantly, all site entries in the SampleID column of dataset 85 list 'Netherlands' followed by what now appears to be the sample depth listed twice, whereas the original dataset includes lat/longs as well as depth in separate columns. 

Example (Dataset 85 site entry): Netherlands_28_28

Is there any reason that we should be using dataset 85 from the raw datasets folder instead of the original dataset from EMODnet? It seems like the original includes more years of sampling and it also includes lat/longs, which would be better site indicators than depth.

**Comment by ahhurlbert** [comment]
@wlarsen2 

Yes. Please download this other raw dataset and replace the one currently in the data/raw_datasets folder.

Process as a lat-long dataset.

**Comment by ahhurlbert** [comment]
As a marine dataset with samples only given by lat-longs, this dataset is inappropriate for current purposes. Closing issue.
