### ISSUE TITLE
Konza / Ft. Riley birds dataset

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#54]
Rivers et al. 2010. Long-Term Community Dynamics of Small Landbirds with and Without Exposure to Extensive Disturbance from Military Training Activities. Environmental Management 45: 203-216.

Has tables with temporal occupancy for "small landbirds" at both Konza Prairie and Ft. Riley Kansas over 1991-2001.

Konza data is a subset of the full time series available, but not sure the Ft. Riley data is available any where else.

**Comment by ssnell6** [comment]
Konza and Ft Riley formatted using partial data cleaning script bc occupancies already in raw data. Konza is d270, Ft Riley is d271
