### ISSUE TITLE
spatial grain confusion

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#60]
For dwork 279, I got to spatial grain (R code line 712) and got stuck when I got an error for all combinations and trying just the largest grain. I'm going to save and stop here until I can get this resolved and pushing to git resolved.

Thanks!

**Comment by ahhurlbert** [comment]
@ssnell6 I can't really troubleshoot this until I can see the code, so see if you can get it added and pushed properly as I suggested in response to your other issue, then I can take a look.

**Comment by ahhurlbert** [comment]
Apparently I helped resolve this in December.
