### ISSUE TITLE
git issue

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#65]
I don't think I did anything to disconnect myself from git, but it's not picking up when I edit files. I formatted dataset 258 and it's not on github in the data files, script, or data formatting table. When I call git status on core-transient it says everything is up to date. Google didn't yield anything helpful except perhaps it's an upstream problem.

**Comment by ahhurlbert** [comment]
Realized we had forked a second repository by accident. All fixed now.
