### ISSUE TITLE
new dataset to incorporate: MERP

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#70]
Marsh Ecology Research Program

Data on KNB:
https://knb.ecoinformatics.org/#view/doi:10.5063/AA/bowdish.819.26

**Comment by ssnell6** [comment]
Dataset was determined to be unsuitable due to different sampling methods over the sampling period, with no more than 4 consecutive years of the same sampling methods/efforts/etc. Confirmed with Allen.
