### ISSUE TITLE
Make sure we have all of the datasets in Yenni et al. 2016

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#72]
See her Appendix S1 at http://biorxiv.org/content/early/2016/02/19/040360.figures-only

**Comment by ssnell6** [comment]
Do we know anything about mountain bird watch? The data download takes me here and there doesn't seem to be any data just desciption of the data and instructions: http://www.birdscanada.org/birdmon/default/resources.jsp

Mountain birdwatch also isn't listed in their dataset download form.

I can email them directly at mbw@vtecostudies.org if there isn't knowledge about the dataset

**Comment by ssnell6** [comment]
Lots of data is linked to being here: https://www.imperial.ac.uk/cpb/gpdd

but I get an error when I try to register to access the data. Does anyone know how to use this database or is the site just down temporarily?

**Comment by ssnell6** [comment]
International Bottom Trawl Survey data link led to a huge zip file which doesn't seem to have species data attached to it

http://ocean.ices.dk/Project/IBTS/

**Comment by ssnell6** [comment]
For the Cowley snakes, they organized the data summed by site or summed by years so you couldn't get both site and year. I went with year since we need the temporal data but wanted to double check.

**Comment by ssnell6** [comment]
This link just takes to you an email address for George Pisani at the Kansas Biological Survey, should I contact him for the full dataset? "broader information on bird abundance and natural communities in the region can be obtained by contacting the Kansas Biological Survey"

http://kufs.ku.edu/media/kufs/libres/snakedata.htm

**Comment by ssnell6** [comment]
Need to contact Haven Wiley for Coweeta salamanders data.

**Comment by ssnell6** [comment]
Need to check out Long-term Studies of Vertebrate Communities from a library to get Rainbow Bay Frogs

**Comment by ssnell6** [comment]
Need to check out Marine Mammals and Fisheries book from a library to get CA coastline molluscs data

**Comment by ssnell6** [comment]
We don't have Jornada arthropod data correct? I only see d215 which is plants.

**Comment by ssnell6** [comment]
d306 (long term trends in Lepidoptera in hardwood forests, Hubbard brook LTER) richnesstest function is throwing an error, I suspect because of spatial grain. It had 4 potential site grains so I need help figuring out which one(s) to use

**Comment by ethanwhite** [comment]
@gmyenni - Is this, https://github.com/gmyenni/RareStabilizationData,  the associated data from your preprint? Can we integrate anything we don't have yet into the data we're putting together to look at core-transient dynamics?

**Comment by ssnell6** [comment]
Thanks @ethanwhite! I'll wait for confirmation that we can use the data before moving forward with cleaning it.

**Comment by ssnell6** [comment]
For the Great Basin mammal abundance (d307), I am getting a failed richness years test. The dates range from 1962-1993 and there are 2 sites that span more than 6 years (lengthYears =33 for both).

**Comment by gmyenni** [comment]
Yes, that repo has all the data, as I used them in the paper. I think the only one you for which you need your own written permission is the Fitch snake data (Kansas Biological Survey).

**Comment by ethanwhite** [comment]
Awesome. Thanks @gmyenni!

**Comment by ssnell6** [comment]
Do we want to include this in our analysis? "The North American Breeding Bird Survey Results and Analysis. Version 96.4. Patuxent Wildlife Research Center" Pawnee songbirds and raptors. Seems like a subset of our dataset 1 (all of BBS) and I don't want to double count. 

dataset is from rarestabilizationdata and is the "shortgrass steppe" under birds

**Comment by ssnell6** [comment]
done
