### ISSUE TITLE
d309 count classification

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#74]
d309 is the international bottom trawl survey.  The count data provided is in average catch/hour. I wanted to raise the issue because the data is skewed towards 90-100% occupancy and I am concerned it could be because we are using the rate value as a raw count. However, little information has been provided about the survey methods and the only things I came with as potential solutions are that they specified that "A standard tow should be fished for 30 minutes" (p 21) to eliminate the rate part of the count or that 214 hauls were conducted total, but it was not specified if this changed by year, was a yearly value, or a total value (p 9). If there is another metric that could be promising let me know and I will search for it in the document

http://www.slu.se/Documents/externwebben/akvatiska-resurser/personliga%20sidor/Ann-Christin%20Rudolphi/2010%20IBTS%20Manual_Rev_VIII.pdf

**Comment by ahhurlbert** [comment]
This dataset only includes a "selection" of species for monitoring, i.e. not everything, so transient species are likely underrepresented. Dataset is not being included in analysis.
