### ISSUE TITLE
d310 no acceptable sites

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#75]
Getting error for richnessYearsTest: "No acceptable sites, rethink site definitions or temporal scale"

We don't have site-specific data, just the species found per year at the biological station. The temporal scale is 14 years. 

This is the same issue as Hubbard Brook (d306), which also only has 1 site.

**Comment by ahhurlbert** [comment]
Add a site column that just equals 1 all the way down, and re-run.

**Comment by ssnell6** [comment]
Ok I will try this for 310 as well

**Comment by ssnell6** [comment]
I am getting the same error for both scripts after adding a site = 1 column

**Comment by ssnell6** [comment]
It was because of the minspecies requirement.
