### ISSUE TITLE
make sure meanAbundance for a dataset is calc'd AFTER filters

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#78]
For d67 (coordinated waterbird counts, South Africa), there are >400 unique sites but only 46 make it through the relevant filters to be analyzed for temporal occupancy.

However, the meanAbundance value seems to get calculated before that filter takes place (and so is very low, including sites with very low coverage, numbers of species, numbers of years).

**Comment by ssnell6** [comment]
The script removed mean abundance in line 647 bc its not reliable. When I reran the script they are all NA in siteSummaries

# REMOVE meanAbundance info which is unreliable (see notes above)
summ$meanAbundance = NA
