### ISSUE TITLE
d41 lat-longs and dataset name, and other Preston data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#80]
d41 is referred to as "Breeding Birds from Preston 1948" in the data formatting table, but this is incorrect. It should be "Breeding Birds from Preston 1960".

The dataset available in the linked data_source (http://www.jstor.org/stable/1931793) only has data for a single site, Neotoma in Ohio, and so this lat-long should be restored to the data formatting table. This is the data in raw_datasets/dataset_41.csv

The Preston 1948 Ecology paper ALSO has two additional datasets that we can use, neither of which is currently in the data formatting table as far as I can tell. These are the Saskatoon moth light trap data, and the Lethbridge moth light trap data.

They should be added manually to the data_formatting_table with as much metadata as possible, but they do not require cleaning scripts because the raw data are unavailable, only the temporal occupancy data (number of years present out of 22 years, on page 276). So these can be entered manually as propOcc datasets and siteSummary datasets.

Paper here: http://www.jstor.org/stable/1930989

**Comment by ssnell6** [comment]
Preston 1948 added as d319 and d320.

DFT fixed also.
