### ISSUE TITLE
file cleaning

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#83]
@ssnell6 Go ahead and clean up both data cleaning script files and raw dataset files.

Remove any files for datasets which are no longer listed in the data formatting table.

For datasets where there are duplicate cleaning scripts (e.g., with different initials appended), identify which clean script is the more outdated and remove it.

Remember you can do this from Git Bash by typing 

`git rm <filename>`

Then `git commit` and `git push` as usual.

**Comment by ssnell6** [comment]
Removed excess files for cleaning scripts, moved excess files into dataset folders for raw datasets/deleted when necessary.
