### ISSUE TITLE
Raw_spatial_grain_unit in cleaning script template

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#85]
There was an error in line 296 of the data_formatting_template.R

('Raw_spatial_grain_unit' was previously and incorrectly 'Raw_spatial_grain')

The result was that for every dataset, the Raw_spatial_grain_unit field in the data_formatting_table was filled with a repeat of the quantitative spatial grain values rather than the scientific units describing those values which did not get recorded anywhere (even though the user may have indicated them in the cleaning script).

@ssnell6 please revisit this section of each cleaning script, and make sure the appropriate section looks like this:

dataFormattingTable[,'Raw_spatial_grain_unit'] = 
  dataFormattingTableFieldUpdate(datasetID, 'Raw_spatial_grain_unit',

**Comment by ahhurlbert** [comment]
Actually, this would be a great opportunity to learn how to write a shell script that finds and replaces a text string!

E.g., http://stackoverflow.com/questions/15402770/how-to-grep-and-replace

**Comment by ssnell6** [comment]
fixed this, should be reflected in the DFT
