### ISSUE TITLE
re-cleaning d207, site identifiers

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#87]
@ssnell6 I noticed a few issues with this dataset which I'll post in separate issues.

First, site identifiers:

1) Site is hierarchical, with quadrats nested within blocks (From metadata: " In this file the quadrats were renamed to B1Q1 style where the number following the B is block number and the number following Q is quadrat number.") 

2) These quadrats are so small, that even a group of 5 of them in a block is probably small to define an "assemblage", which means we want to add a constant site identifier (e.g. "Toolik") as the highest spatial grain, allowing us to aggregate all quadrats together if necessary. This means ultimately, the 'site' field will look like this "Toolik_1_1" to refer to quadrat 1 inside block 1 at Toolik.

**Comment by ssnell6** [comment]
made a site final column to address the hierarchy.

I will leave the spatial scale as is for now, and we can look at the results later to see if we need to scale up.
