### ISSUE TITLE
re-cleaning d207, removing non-quadrats

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#88]
@ssnell6 

Do a quick check of the unique values of 'quadrat', and how many times they occur:
`table(dataset$quadrat)`
You will see several things. First, each block-quadrat combo occurs twice, but the second time it has 'gm2' appended to the end. I re-checked the metadata and a spotcheck indicates that the rows with 'gm2' in the quadrat name are duplicates where the biomass value was converted from grams per 0.04 m^2 to grams per m^2. If this is true, all of these gm2 records can be removed. (Although a look at the propOcc file reveals differences between, e.g., B1Q1 and B1Q1gm2 with occ values differing, and even specieslists differing; so we probably need to better understand what's going on here.)

Second, there are quadrats labeled "Average", "Count", and "Std..Err." which presumably need to get removed.

**Comment by ssnell6** [comment]
I thought that we would want the dried biomass values attached to each B1Q1 label for count data rather than one of the original columns. Do you mean that in addition to the columns there are also rows with averages/counts/std errors in the quadrat field?

**Comment by ahhurlbert** [comment]
Yes, exactly. Type this:
`table(dataset$quadrat)`

**Comment by ssnell6** [comment]
removed the avg/count/SE quadrats. I will go through the metadata to figure out whats going on w gm2

**Comment by ssnell6** [comment]
removed all gm2 - couldn't distinguish additional differences besides unit changes in the raw datasets.
