### ISSUE TITLE
re-cleaning d207, "biomass" category for count data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#90]
@ssnell6 Finally, let's add a new 'biomass' option to the metadata on count type. And note that for this dataset, we'll be ignoring tissue and just summing up the biomass values by species within each quadrat (which will happen automatically when dataset7 is created using ddply).

In the notes you might mention that the biomass in our formatted dataset has been summed across tissue types, including both aboveground and belowground biomass.

**Comment by ssnell6** [comment]
done - updated template and d207 script. Noted aboveground & belowground biomass sum in notes for DFT.
