### ISSUE TITLE
re-cleaning d207, sample dates

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#91]
@ssnell6 Just noticed that number of sample dates varies by year, with 1983 having 5 separate dates, while many other years only have 1 sample date. Technically, our algorithm will adjust for this by randomly subsampling from available dates, but in this case, every year is sampled within a week of the end of July, whereas 1983 has sample dates as early as May and as late as late-August. That will make a huge difference up in the arctic tundra, so I suggest we subset all data to just sample dates in July, which should just be one date per year.

**Comment by ssnell6** [comment]
done - maybe not the most elegant, but inserted code on lines 172-175 of cleaning script
