### ISSUE TITLE
problem with raw data for d315

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#94]
A comment from @lauraantao:

I was trying to adapt the dataset ID 315 (Monitoring the Abundance of Butterflies 1976-1985). I copied the records from the github repo, and I have 98 records with count= "NA"; 25 of these have "SampleYear" =1985, but the remaining ones have "Status API Training Shop Blog About Pricing" and "? 2016 GitHub, Inc. Terms Privacy Security Contact Help". Could you please let me know if this is ok? Or if it is caused by some problem getting the file from github?

@ssnell6 could you please take a look?

**Comment by ssnell6** [comment]
@lauraantao - thank you for bringing this to our attention. I had acquired the raw data files from another repo and it was originally separated into 5 text files, which I pasted together in R. One of the files I copied also copied the bottom of the webpage and it got incorporated into the bottom of the dataset. I just reran the formatting script to paste together the datasets without that extra line from the webpage and the corrected dataset 315 raw data file is now on our repo.

**Comment by lauraantao** [comment]
Thank you for looking into it so quickly!

Best
Laura

On Friday, 20 May 2016, ssnell6 <notifications@github.com> wrote:

> @lauraantao <https://github.com/lauraantao> - thank you for bringing this
> to our attention. I had acquired the raw data files from another repo and
> it was originally separated into 5 text files, which I pasted together in
> R. One of the files I copied also copied the bottom of the webpage and it
> got incorporated into the bottom of the dataset. I just reran the
> formatting script to paste together the datasets without that extra line
> from the webpage and the corrected dataset 315 raw data file is now on our
> repo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hurlbertlab/core-transient/issues/94#issuecomment-220705827>[image:
> Web Bug from
> https://github.com/notifications/beacon/AMUDzh8GUi21TMD9LtAmu2GPWQ17cFEpks5qDhQzgaJpZM4Ijc10.gif]
>


-- 
Laura Antão
PhD Student – University of St Andrews & University of Aveiro
Centre for Biological Diversity
Sir Harold Mitchell Building
KY16 9TH, St Andrews, UK
e-mail: *liha@st-andrews.ac.uk <liha@st-andrews.ac.uk>* & laura.antao@ua.pt
