### ISSUE TITLE
new dataset: UHURU small mammals and others?

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#95]
Grab data and complete cleaning script for small mammal community data

http://www.esapubs.org/archive/ecol/E095/064/metadata.php

**Comment by ssnell6** [comment]
I will look into the plant datasets but the small mammals dataset only has 4 years of data (2009-2012). I started the script and I can change minNTime if you think we should, but 4 years seems a little short.

**Comment by ssnell6** [comment]
These two datasets seem to fit our criteria if we reduce minNTime to 5 years. 

(7) Biannual surveys of understory composition within 49 larger (1-m²) quadrats per plot - Yearly understory vegetation data recorded in large quadrats (1 m²) at each rebar.

We'd have to increase plot size to make this one work I think.

(8) Annual size measurements of a subset of tagged and mapped trees within each plot - number of individuals of each species in each size class in each year per plot.

**Comment by ssnell6** [comment]
For biannual plant survey (d322), I couldn't get the month converted from text to numeric. I tried in the preformatting script. 
There could be something off with the sites since the species occurrences were even. I remember that was an issue in another script but I couldn't find anything weird about the sampling methods - maybe adding month in will help. Right now the vast majority of occurrences are transient, so we probably need to scale up site. I will wait for confirmation before changing it.

After fixing these errors, d322 is complete.

**Comment by ahhurlbert** [comment]
I'll take a look at d322 but it looks like the data files have not been pushed yet.

**Comment by ahhurlbert** [comment]
Didn't realize mammals only have 4 years of data--we won't pursue them further.

**Comment by ssnell6** [comment]
The original d322 file was too large so I zipped and I thought it went through. I'll try to fix that

**Comment by ssnell6** [comment]
I can't get the original or the zip to upload to github. I tried a hard reset and it's not recognizing the new files now, so I'm not sure what's wrong. I'm going to try to recreate my local data repo

**Comment by ahhurlbert** [comment]
Looks like there is a file in the dataset_322RAW folder, there's just nothing in the regular raw_datasets folder, so the cleaning script does not load any data file. Seems like you can just move the file over?

**Comment by ssnell6** [comment]
I tried that and the file was too big. working on recloning now

**Comment by ssnell6** [comment]
I reset everything and I'm still getting the size limit error even though I have only d322 zipped in my local folder. The zip file is 7,000 kb (which is only 7 MB right?) and the limit is 100 MB so I'm not sure where my large file is hiding. I'll try to figure out where it is tomorrow.

**Comment by ssnell6** [comment]
Got everything resolved so everything should be up to date in repo. I checked to make sure your additions to d287 wasn't lost. I will look into the tree dataset soon.

**Comment by ssnell6** [comment]
Not enough species for d323.

**Comment by ahhurlbert** [comment]
d322 is all set; d323 is not a suitable dataset and has been deleted from data formatting table, etc.
