### ISSUE TITLE
source of d317 data

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#96]
@ssnell6 acquired data from @gmyenni s repo here: https://github.com/gmyenni/RareStabilizationData/tree/master/Mammals

but I'm having trouble reconciling with the raw data files from their source here:
http://dataknp.sanparks.org/sanparks/metacat/peggym.117.10/sanparks

Ideally for Core-Transient, we want to start with the original raw data files (as available on Dryad, Archives, the sanparks.org site above) so which of the raw files listed went into the files on @gmyenni's repo? Need to revisit

**Comment by ssnell6** [comment]
Redid with raw census data
